/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.action;

import java.io.IOException;
import java.util.Iterator;
import java.util.Set;
import java.util.TreeMap;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
/** 
 * MyEclipse Struts
 * Creation date: 02-24-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GenChartAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		response.setHeader("Cache-Control","no-cache");
		response.setHeader("Pragma", "no-cache");
		
		//System.out.println( "\n\nGen Chart" );
		String attrName = request.getParameter("name");
		//System.out.println( "HashMap name:" + attrName );
		String chartName = request.getParameter("chartName");
		//System.out.println( "HashMap name:" + chartName );
		
		try {
			ServletOutputStream out = response.getOutputStream();
			DefaultPieDataset  pieDataset = new DefaultPieDataset ();
			
			TreeMap map = (TreeMap) request.getSession().getAttribute( attrName );
			//System.out.println( map );
			
			Set keys = map.keySet();
			Iterator keyIter = keys.iterator();
			while( keyIter.hasNext() ){
				String key = (String) keyIter.next();
				int count = ( (Integer)map.get(key) ).intValue();
				System.out.println( key + ":" + count );
				pieDataset.setValue(key, count);
			}
			
			JFreeChart chart = ChartFactory.createPieChart(chartName, pieDataset, true, false, false);
			PiePlot plot = (PiePlot) chart.getPlot();
			plot.setForegroundAlpha(0.5f);

			
			response.setContentType("image/png");
			ChartUtilities.writeChartAsPNG(out, chart, 640, 480);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		
		return null;
	}
	

}