/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ibm.cn.db2.mytable.db.CustomerNameDAO;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2008
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="table" path="/webPages/table.jsp"
 */
public class InitialTableAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String name = (String) request.getSession().getAttribute("custName");
		System.out.println( "inital table, name=" + name );
		request.setAttribute("custNameList", CustomerNameDAO.getInstance().getAllCustomerName());
		if( name != null && name.trim().length()>0 ){
			request.setAttribute("myIDList", CustomerNameDAO.getInstance().getAllCustomerID(name));
		}
		
		return mapping.findForward("table");
	}
}