/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.action;

import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.ibm.cn.db2.mytable.db.CustomerNameDAO;

/** 
 * MyEclipse Struts
 * Creation date: 02-22-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="index" path="/webPages/index.jsp"
 */
public class InitialAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ArrayList all = CustomerNameDAO.getInstance().getAllCustomerName();
		request.getSession().setAttribute("custNameList", all);
		
		request.getSession().removeAttribute("custData");
		request.getSession().removeAttribute("query");
		request.getSession().removeAttribute("db");
		request.getSession().removeAttribute("page");
		
		return mapping.findForward("index");
	}
}