/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.action;

import java.sql.ResultSet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.ibm.cn.db2.mytable.cqdb.PmrDAO;
import com.ibm.cn.db2.mytable.db.NativePmrDAO;
import com.ibm.cn.db2.mytable.struts.form.QueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-17-2008
 * 
 * XDoclet definition:
 * @struts.action path="/query" name="queryForm" input="/webPages/query.jsp" scope="request" validate="true"
 */
public class QueryAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryForm queryForm = (QueryForm) form;
		
		/*form already validated*/
		String custID = queryForm.getCustID(); 
		String dbMenu = queryForm.getDbMenu();
		
		//System.out.println("Queried ID:" + custID + ", Queried db:" + dbMenu);
		
		if( dbMenu.compareTo("wkly") == 0 || dbMenu.compareTo("hist") == 0 ||dbMenu.compareTo("archive") == 0 ){
			//从CQDB取出来的东东，不支持分页！
			request.getSession().setAttribute("db", dbMenu);
			request.getSession().removeAttribute("custData");
			ResultSet rs = PmrDAO.getInstance().getAll(custID, dbMenu);
			int count = NativePmrDAO.getInstance().insert(rs);
			
			String responseString = count + " results found <br />and inserted to Local DB";
			request.setAttribute( "responseString", responseString );
		} else if( dbMenu.compareTo("retrieve") == 0){
			//从自己的数据库中取出的东东，支持分页！
			//int p=(request.getAttribute("page")==null)?0:Integer.parseInt((String)request.getAttribute("page"));
			/*int p=1;
			//System.out.println( p );
			
			ArrayList a = NativePmrDAO.getInstance().getAllByPage(custID, 0, PageUtil.PAGESIZE-1, PMRDimention.PROB_CLOSED_DT, false);
			
			int count = NativePmrDAO.getInstance().getResultCount(custID);
			String responseString = count + " results found.";
			System.out.println( responseString );
			
			//我也不想放session里啊，服务器您受苦了！
			request.getSession().setAttribute( "responseString", responseString );
			request.getSession().setAttribute( "totalCount", new Integer(count) );
			
			request.getSession().setAttribute("custData", a);
			request.getSession().setAttribute("page", new Integer(1));
			request.getSession().setAttribute("query", custID);
			request.getSession().setAttribute("db", "retrieve");
			request.getSession().setAttribute("useCustomer", new Boolean(false));*/
			
			request.getSession().setAttribute("totalCount", new Integer(NativePmrDAO.getInstance().getResultCount(custID)) );
			request.getSession().setAttribute("page", new Integer(1));
			request.getSession().setAttribute("query", custID);
			request.getSession().setAttribute("db", "retrieve");
			request.getSession().setAttribute("useCustomer", new Boolean(false));
			
			System.out.println( "Now from query to pagination!" );
			
			//return mapping.findForward("pagination");
			return new ActionForward( "/pagination.do" );
		} else {
			System.out.println( "error db type" );
		}
		
		response.setHeader("Cache-Control","no-cache");
		response.setHeader("Pragma", "no-cache");
		return mapping.findForward("ajax");
	}
}