/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.ibm.cn.db2.mytable.db.NativePmrDAO;
import com.ibm.cn.db2.mytable.util.Util;

/** 
 * MyEclipse Struts
 * Creation date: 02-24-2008
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="refresh" path="/pagination.do"
 */
public class UpdatePmrAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Util.log("updatepmr", request);
		String pmrID = request.getParameter("pmrID");
		String column = request.getParameter("column");
		String value = request.getParameter("value");
		
		NativePmrDAO.getInstance().updatePmrDAO(pmrID, column, value);
		if( column.compareTo("category")==0 ){
			//修改category后应该将subcategory也修改掉！
			column = "subcategory";
			//value = transToSub(value);
			NativePmrDAO.getInstance().updatePmrDAO(pmrID, column, value);
		}
		
		request.setAttribute("responseString", "PMR:" + pmrID + "(" + column +  ") has been updated!");
				
		return new ActionForward( "/pagination.do" );
	}
}