/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ibm.cn.db2.mytable.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.validator.ValidatorActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-17-2008
 * 
 * XDoclet definition:
 * @struts.form name="queryForm"
 */
public class QueryForm extends ValidatorActionForm {
	/*
	 * Generated fields
	 */

	/** custID property */
	private String custID;
	private String dbMenu;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if( custID == null || custID.trim().length() != 7 ){
			errors.add( "custID", new ActionMessage("custID.length") );
		}
		if( dbMenu == null || dbMenu.trim().length() <= 0){
			errors.add( "custID", new ActionMessage("dbMenu.length") );
		}else if( !(dbMenu.compareTo("retrieve") ==0 || dbMenu.compareTo("wkly") ==0 
				|| dbMenu.compareTo("hist") ==0 ||dbMenu.compareTo("archive") ==0 ) ){
			errors.add( "custID", new ActionMessage("dbMenu.type") );
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the custID.
	 * @return String
	 */
	public String getCustID() {
		return custID;
	}

	/** 
	 * Set the custID.
	 * @param custID The custID to set
	 */
	public void setCustID(String custID) {
		this.custID = custID;
	}

	public String getDbMenu() {
		return dbMenu;
	}

	public void setDbMenu(String dbMenu) {
		this.dbMenu = dbMenu;
	}
}